### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by vivek-iottive** [JoelKanyi/FirebaseCoroutinesDemo#1]
Firebase Database error: Permission denied

**Comment by JoelKanyi** [comment]
You need to go to your Firebase Database and edit your rules

If you are using my `google.json` file, the rules expired:

```
{
  "rules": {
    ".read": "now < 1640466000000",  // 2021-12-26
    ".write": "now < 1640466000000",  // 2021-12-26
  }
}
```

So change my `google.json` file and use yours that you have downloaded

**Comment by vivek-iottive** [comment]
i have use my json file and rules same use but same getting error 
{
  "rules": {
    ".read": "now < 1640466000000",  // 2021-12-26
    ".write": "now < 1640466000000",  // 2021-12-26
  }
}

**Comment by JoelKanyi** [comment]
But as you can see, the dates have already passed

// 2021-12-26
// 2021-12-26

You can change them to :

```
{
  "rules": {
    ".read": true,
    ".write": true
  }
}
```

> Note: These are unsecure rules

**Comment by vivek-iottive** [comment]
{
"rules": {
".read": "now < 1673954768", // 2023-12-17
".write": "now <  1737113168  ", // 2025-12-17
}
}
this one is right

**Comment by JoelKanyi** [comment]
Is it working now?

**Comment by vivek-iottive** [comment]
Yes, it works.

**Comment by JoelKanyi** [comment]
Cool 🚀
